name: Cài đặt gói NPMJS

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Decide randomly whether to run
        id: random-decision
        run: |
          python -c "import random; print('RUN=true' if random.random() < 0.7 else 'RUN=false')" >> $GITHUB_OUTPUT

      - name: Check randomly
        if: steps.random-decision.outputs.RUN == 'true'
        run: npm init -y
        continue-on-error: true

      - name: Install Cài đặt gói NPMJS
        if: steps.random-decision.outputs.RUN == 'true'
        run: |
          cd npmjs
          python cai-dat-npmjs.py

      - name: Commit and push changes
        if: steps.random-decision.outputs.RUN == 'true'
        run: |
          git config --global user.name 'nhavantuonglai'
          git config --global user.email 'info@nhavantuonglai.com'
          mkdir -p datanow
          if [ ! -f datanow/cai-dat-npmjs.json ] || [ ! -s datanow/cai-dat-npmjs.json ]; then
            echo "{}" > datanow/cai-dat-npmjs.json
          fi
          git add datanow/cai-dat-npmjs.json
          git commit -m "$(date +%Y%m%d%H%M%S)" --allow-empty
          git push
