name: Cập nhật gói NPMJS

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-downloads:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate downloads NPMJS
        run: |
          cd npmjs
          .\npmjs.bat --generate-json

      - name: Commit and push changes
        run: |
          git config --global user.name 'nhavantuonglai'
          git config --global user.email 'info@nhavantuonglai.com'
          git add datanow/nhavantuonglai.json
          git commit -m "Cập nhật dữ liệu $(date +%Y%m%d)" || echo "Không có mô tả đính kèm."
          git push