name: Kiểm tra gói NPMJS

on:
  schedule:
    - cron: '*/60 * * * *'
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install requests

      - name: Check NPMJS
        run: |
          python npmjs/kiem-tra-npmjs.py --generate-json

      - name: Commit and push changes
        run: |
          git config --global user.name 'nhavantuonglai'
          git config --global user.email 'info@nhavantuonglai.com'
          if [ -f datanow/nhavantuonglai.json ]; then
            git add datanow/nhavantuonglai.json
            git commit -m "Cập nhật dữ liệu $(date +%Y%m%d)" --allow-empty
            git push
          else
            echo "Tệp datanow/nhavantuonglai.json không tồn tại, bỏ qua commit."
            exit 1
          fi