name: Kiểm tra gói NPMJS

on:
  schedule:
    - cron: '*/60 * * * *'
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install requests

      - name: Check NPMJS
        run: |
          python npmjs/kiem-tra-npmjs.py --generate-json nhavantuonglai

      - name: Commit and push changes
        run: |
          git config --global user.name 'nhavantuonglai'
          git config --global user.email 'info@nhavantuonglai.com'
          mkdir -p datanow
          if [ ! -f datanow/kiem-tra-npmjs.json ] || [ ! -s datanow/kiem-tra-npmjs.json ]; then
            echo "{}" > datanow/kiem-tra-npmjs.json
          fi
          git add datanow/kiem-tra-npmjs.json
          git commit -m "Cập nhật dữ liệu $(date +%Y%m%d%H%M%S)" --allow-empty
          git push
