name: Truy vấn từ khóa

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip tor firefox libu2f-udev
          # Tải và cài đặt geckodriver
          curl -sL https://github.com/mozilla/geckodriver/releases/download/v0.35.0/geckodriver-v0.35.0-linux64.tar.gz | tar -xz -C /usr/local/bin
          sudo chmod +x /usr/local/bin/geckodriver
          # Cấu hình Tor
          echo "ControlPort 9051" | sudo tee -a /etc/tor/torrc
          echo "CookieAuthentication 1" | sudo tee -a /etc/tor/torrc
          sudo systemctl start tor
          sudo systemctl enable tor
          # Debug: Kiểm tra đường dẫn
          which firefox
          which geckodriver
          geckodriver --version

      - name: Install Python dependencies
        run: |
          pip install selenium webdriver-manager requests stem

      - name: Install Truy vấn từ khóa
        run: |
          python npmjs/truy-van-tu-khoa.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'nhavantuonglai'
          git config --global user.email 'info@nhavantuonglai.com'
          mkdir -p datanow
          git add datanow/truy-van-tu-khoa.json
          git commit -m "Truy vấn từ khóa $(date +%Y%m%d%H%M%S)" --allow-empty
          git push