name: python-indexnow-push

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at 00:00 UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  submit-url:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.python_indexnow }}

      - name: List repository files
        run: dir
        shell: cmd
        working-directory: indexnow

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path indexnow/requirements.txt) { pip install -r indexnow/requirements.txt }
        shell: pwsh

      - name: Run indexing.bat
        run: |
          cd indexnow
          .\indexing.bat
        shell: cmd
        continue-on-error: true

      - name: Run indexnow.bat
        run: |
          cd indexnow
          .\indexnow.bat
        shell: cmd
        continue-on-error: true

      - name: Commit and push results.json
        run: |
          cd indexnow
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add results.json
          git commit -m "Update results.json with new run data" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.python_indexnow }}
        shell: cmd